server: 
  port: 9001
  servlet: 
    context-path: /
spring: 
  application:  
    name: weisheng-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weisheng_user?characterEncoding=UTF8
    username: root
    password: 123

  devtools:
    restart:
      # 热部署开关
      enabled: true    
mybatis:
    # 搜索指定包别名
#    typeAliasesPackage: com.weisheng.entity
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/*Mapper.xml
    # 加载全局的配置文件
#    configLocation: classpath:mybatis/mybatis-config.xml  


#  jpa: 
#    database: mysql
#    show-sql: true
# 日志配置
#logging:
#  level:
#    com.weisheng: debug
#    org.springframework: warn
# MyBatis配置
  
#eureka:
#  client:
#    service-url:
#       defaultZone: http://127.0.0.1:6868/eureka/ # 表示去这个url注册或者拿取
#  instance:
#    prefer-ip-address: true # 用来允许跨域访问
#feign:
#  hystrix:
#   enabled: true